name: siente_app
description: A new Flutter project.

publish_to: "none"

version: 13.1.0+14

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  custom_marker: ^1.0.0
  dio: ^5.0.3
  fluster: ^1.2.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.0.1
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  intl: ^0.17.0
  marquee_widget: ^1.2.0
  photo_view: ^0.14.0
  shared_preferences: ^2.0.18
  syncfusion_flutter_gauges: ^20.4.54

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_foreground: "assets/launcher/icon.png"

flutter_assets:
  assets_path: assets/
  output_path: lib/app/assets
  package: module_home
  compress_images: false

flutter:
  uses-material-design: true
  assets:
    - assets/new/login/
    - assets/new/splash/
    - assets/new/home/
    - assets/new/details/
